codecov:
  require_ci_to_pass: yes

coverage:
  status:
    patch: no
    project:
      default:
        threshold: 1%
        if_not_found: success
    changes: no

  precision: 2
  range: 50...75

  notify:
    irc:
      default:
        server: chat.freenode.net
        channel: '##allieae'
        branches: master
        threshold: 2
        message: null

ignore:
 - "test/.*"
 - ".tox/.*"
 - "scripts/.*"
 - "*.rst"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  # layout: "reach, diff, flags, tree"
  branches: null
  behavior: default
  require_changes: no
