dist: xenial
language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "nightly"

# command to install dependencies
install: pip install tox-travis pytest pytest-pep8 pytest-flake8

# command to run tests (no tests yet)
script:
  - tox

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

