dist: xenial
language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "nightly"

# command to install dependencies
install:
  - "pip install pytest"
  - "pip install pytest-pep8"
  - "pip install pytest-flake8"

# command to run tests (no tests yet)
script:
  - pytest --pep8 --flake8 node_tools/ scripts/

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

