language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "nightly"

# command to install dependencies
install:
  - pip install pytest
  - pip install pytest-pep8
  - pip install pytest-flake8
  - pip install tox-travis

# command to run tests (no tests yet)
script:
  - tox

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

notifications:
  irc:
    channels:
      - "irc.freenode.org#code-hell"
      - "irc.freenode.org#allieae"
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: false     # default: false

